DoAnWeb-KetNoiViecLam/DoAnWeb-KetNoiViecLam/Controllers/UserDashboardController.cs
using DoAnWeb_KetNoiViecLam.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace DoAnWeb_KetNoiViecLam.Controllers
{
    public class UserDashboardController : Controller
    {
        private readonly DataContext _dataContext;

        public UserDashboardController(DataContext dataContext)
        {
            _dataContext = dataContext;
        }

        public IActionResult Dashboard()
        {
            return View();
        }

        public IActionResult ManageServices()
        {
            var serviceList = _dataContext.ServiceInformations.ToList();
            return View(serviceList);
        }

        [HttpGet]
        public IActionResult AddService()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddService(ServiceInformation model)
        {
            if (ModelState.IsValid)
            {
                model.Status = "active";
                _dataContext.ServiceInformations.Add(model);
                _dataContext.SaveChanges();
                return RedirectToAction("ManageServices");
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult EditService(int id)
        {
            var service = _dataContext.ServiceInformations.Find(id);

            if (service == null)
            {
                return NotFound();
            }
            return View(service);
        }

        [HttpPost]
        public IActionResult EditService(ServiceInformation model)
        {
            if (ModelState.IsValid)
            {
                // Lấy đối tượng từ cơ sở dữ liệu
                var existingService = _dataContext.ServiceInformations.SingleOrDefault(s => s.ServiceID == model.ServiceID);

                if (existingService != null)
                {
                    // Cập nhật thông tin của đối tượng
                    existingService.ServiceTitle = model.ServiceTitle;
                    existingService.Price = model.Price;
                    existingService.Category = model.Category;
                    existingService.EnglishLevel = model.EnglishLevel;
                    existingService.ResponseTime = model.ResponseTime;
                    existingService.DeliveryTime = model.DeliveryTime;
                    existingService.Skills = model.Skills;
                    existingService.Address = model.Address;
                    existingService.ServiceDetail = model.ServiceDetail;
                    existingService.Status = "active"; // Không cần gán lại model.Status

                    // Lưu thay đổi vào cơ sở dữ liệu
                    try
                    {
                        _dataContext.SaveChanges();
                    }
                    catch (Exception ex)
                    {
                        // In ra lỗi để kiểm tra
                        Console.WriteLine(ex.Message);
                    }
                    return RedirectToAction("ManageServices");
                }
                else
                {
                    return NotFound();
                }
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult DeleteService(ServiceInformation model)
        {
            if (ModelState.IsValid)
            {
                var existingService = _dataContext.ServiceInformations.SingleOrDefault(s => s.ServiceID == model.ServiceID);
                if (existingService == null)
                {
                    return NotFound();
                }
                _dataContext.ServiceInformations.Remove(existingService);
                _dataContext.SaveChanges();

            return RedirectToAction("ManageServices");
            }
        }

    }
}

DoAnWeb-KetNoiViecLam/DoAnWeb-KetNoiViecLam/Views/UserDashboard/DeleteService.cshtml
@model DoAnWeb_KetNoiViecLam.Models.ServiceInformation;
@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<div class="dashboard__content hover-bgc-color">
    <div class="row pb40">
        <div class="col-lg-12">
            <div class="dashboard_navigationbar d-block d-lg-none">
                <div class="dropdown">
                    <button onclick="myfunction()" class="dropbtn"><i class="fa fa-bars pr10"></i> dashboard navigation</button>
                    <ul id="mydropdown" class="dropdown-content">
                        <li><p class="fz15 fw400 ff-heading mt30 pl30">start</p></li>
                        <li><a href="page-dashboard.html"><i class="flaticon-home mr10"></i>dashboard</a></li>
                        <li><a href="page-dashboard-proposal.html"><i class="flaticon-document mr10"></i>my proposals</a></li>
                        <li><a href="page-dashboard-save.html"><i class="flaticon-like mr10"></i>saved</a></li>
                        <li><a href="page-dashboard-message.html"><i class="flaticon-chat mr10"></i>message</a></li>
                        <li><a href="page-dashboard-reviews.html"><i class="flaticon-review-1 mr10"></i>reviews</a></li>
                        <li><a href="page-dashboard-invoice.html"><i class="flaticon-receipt mr10"></i>invoice</a></li>
                        <li><a href="page-dashboard-payouts.html"><i class="flaticon-dollar mr10"></i>payouts</a></li>
                        <li><a href="page-dashboard-statement.html"><i class="flaticon-web mr10"></i>statements</a></li>
                        <li><p class="fz15 fw400 ff-heading mt30 pl30">organize and manage</p></li>
                        <li><a href="page-dashboard-manage-service.html"><i class="flaticon-presentation mr10"></i>manage services</a></li>
                        <li><a href="page-dashboard-manage-jobs.html"><i class="flaticon-briefcase mr10"></i>manage jobs</a></li>
                        <li><a href="page-dashboard-manage-project.html"><i class="flaticon-content mr10"></i>manage project</a></li>
                        <li><p class="fz15 fw400 ff-heading mt30 pl30">account</p></li>
                        <li class="active"><a href="page-dashboard-profile.html"><i class="flaticon-photo mr10"></i>my profile</a></li>
                        <li><a href="page-login.html"><i class="flaticon-logout mr10"></i>logout</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-9">
            <div class="dashboard_title_area">
                <h2>add services</h2>
                <p class="text">lorem ipsum dolor sit amet, consectetur.</p>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="text-lg-end">
                <a href="" class="ud-btn btn-dark">save & publish<i class="fal fa-arrow-right-long"></i></a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-12">
            <div class="ps-widget bgc-white bdrs4 p50 mb30 overflow-hidden position-relative">
                <div class="bdrb1 pb15 mb25">
                    <h5 class="list-title">basic information</h5>
                </div>
                <div class="col-xl-12">
                    <form class="form-style1" method="post" asp-controller="UserDashboard" asp-action="DeleteService">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="mb35">
                                    <label class="heading-color ff-heading fw500 mb10">Service Title</label>
                                    <input type="text" class="form-control" placeholder="i will" asp-for="ServiceTitle">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="mb35">
                                    <label class="heading-color ff-heading fw500 mb10">Price</label>
                                    <input type="text" class="form-control" placeholder="500000vnd" asp-for="Price">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="mb20">
                                    <label class="heading-color ff-heading fw500 mb10">Category</label>
                                    <input type="text" class="form-control" placeholder="coding" asp-for="Category">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="mb20">
                                    <label class="heading-color ff-heading fw500 mb10">English Level</label>
                                    <input type="text" class="form-control" placeholder="level b1" asp-for="EnglishLevel">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="mb20">
                                    <label class="heading-color ff-heading fw500 mb10">Response Time</label>
                                    <input type="text" class="form-control" placeholder="1 day" asp-for="ResponseTime">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="mb20">
                                    <label class="heading-color ff-heading fw500 mb10">Delivery Time</label>
                                    <input type="text" class="form-control" placeholder="" asp-for="DeliveryTime">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="mb20">
                                    <label class="heading-color ff-heading fw500 mb10">Skills</label>
                                    <input type="text" class="form-control" placeholder="write here" asp-for="Skills">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="mb20">
                                    <label class="heading-color ff-heading fw500 mb10">Address</label>
                                    <input type="text" class="form-control" placeholder="" asp-for="Address">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="mb20">
                                <label class="heading-color ff-heading fw500 mb10">Service Detail</label>
                                <textarea type="text" cols="30" rows="6" placeholder="description" asp-for="ServiceDetail"></textarea>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="text-start">
                                <input type="hidden" asp-for="ServiceID" />
                                <button type="submit" class="ud-btn btn-thm">Delete<i class="fal fa-arrow-right-long"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="dashboard__main pl0-md">
</div>

DoAnWeb-KetNoiViecLam/DoAnWeb-KetNoiViecLam/Views/UserDashboard/EditService.cshtml
@model DoAnWeb_KetNoiViecLam.Models.ServiceInformation;
@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<div class="dashboard__content hover-bgc-color">
    <div class="row pb40">
        <div class="col-lg-12">
            <div class="dashboard_navigationbar d-block d-lg-none">
                <div class="dropdown">
                    <button onclick="myfunction()" class="dropbtn"><i class="fa fa-bars pr10"></i> dashboard navigation</button>
                    <ul id="mydropdown" class="dropdown-content">
                        <li><p class="fz15 fw400 ff-heading mt30 pl30">start</p></li>
                        <li><a href="page-dashboard.html"><i class="flaticon-home mr10"></i>dashboard</a></li>
                        <li><a href="page-dashboard-proposal.html"><i class="flaticon-document mr10"></i>my proposals</a></li>
                        <li><a href="page-dashboard-save.html"><i class="flaticon-like mr10"></i>saved</a></li>
                        <li><a href="page-dashboard-message.html"><i class="flaticon-chat mr10"></i>message</a></li>
                        <li><a href="page-dashboard-reviews.html"><i class="flaticon-review-1 mr10"></i>reviews</a></li>
                        <li><a href="page-dashboard-invoice.html"><i class="flaticon-receipt mr10"></i>invoice</a></li>
                        <li><a href="page-dashboard-payouts.html"><i class="flaticon-dollar mr10"></i>payouts</a></li>
                        <li><a href="page-dashboard-statement.html"><i class="flaticon-web mr10"></i>statements</a></li>
                        <li><p class="fz15 fw400 ff-heading mt30 pl30">organize and manage</p></li>
                        <li><a href="page-dashboard-manage-service.html"><i class="flaticon-presentation mr10"></i>manage services</a></li>
                        <li><a href="page-dashboard-manage-jobs.html"><i class="flaticon-briefcase mr10"></i>manage jobs</a></li>
                        <li><a href="page-dashboard-manage-project.html"><i class="flaticon-content mr10"></i>manage project</a></li>
                        <li><p class="fz15 fw400 ff-heading mt30 pl30">account</p></li>
                        <li class="active"><a href="page-dashboard-profile.html"><i class="flaticon-photo mr10"></i>my profile</a></li>
                        <li><a href="page-login.html"><i class="flaticon-logout mr10"></i>logout</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-9">
            <div class="dashboard_title_area">
                <h2>add services</h2>
                <p class="text">lorem ipsum dolor sit amet, consectetur.</p>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="text-lg-end">
                <a href="" class="ud-btn btn-dark">save & publish<i class="fal fa-arrow-right-long"></i></a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-12">
            <div class="ps-widget bgc-white bdrs4 p50 mb30 overflow-hidden position-relative">
                <div class="bdrb1 pb15 mb25">
                    <h5 class="list-title">basic information</h5>
                </div>
                <div class="col-xl-12">
                    <form class="form-style1" method="post" asp-controller="UserDashboard" asp-action="EditService">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="mb35">
                                    <label class="heading-color ff-heading fw500 mb10">Service Title</label>
                                    <input type="text" class="form-control" placeholder="i will" asp-for="ServiceTitle">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="mb35">
                                    <label class="heading-color ff-heading fw500 mb10">Price</label>
                                    <input type="text" class="form-control" placeholder="500000vnd" asp-for="Price">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="mb20">
                                    <label class="heading-color ff-heading fw500 mb10">Category</label>
                                    <input type="text" class="form-control" placeholder="coding" asp-for="Category">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="mb20">
                                    <label class="heading-color ff-heading fw500 mb10">English Level</label>
                                    <input type="text" class="form-control" placeholder="level b1" asp-for="EnglishLevel">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="mb20">
                                    <label class="heading-color ff-heading fw500 mb10">Response Time</label>
                                    <input type="text" class="form-control" placeholder="1 day" asp-for="ResponseTime">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="mb20">
                                    <label class="heading-color ff-heading fw500 mb10">Delivery Time</label>
                                    <input type="text" class="form-control" placeholder="" asp-for="DeliveryTime">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="mb20">
                                    <label class="heading-color ff-heading fw500 mb10">Skills</label>
                                    <input type="text" class="form-control" placeholder="write here" asp-for="Skills">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="mb20">
                                    <label class="heading-color ff-heading fw500 mb10">Address</label>
                                    <input type="text" class="form-control" placeholder="" asp-for="Address">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="mb20">
                                <label class="heading-color ff-heading fw500 mb10">Service Detail</label>
                                <textarea type="text" cols="30" rows="6" placeholder="description" asp-for="ServiceDetail"></textarea>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="text-start">
                                <input type="hidden" asp-for="ServiceID" />
                                <button type="submit" class="ud-btn btn-thm">Edit<i class="fal fa-arrow-right-long"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="dashboard__main pl0-md">
</div>